[connections.snowflake]
account = "NILFYYN-EMB36384"
user = "GIT"
password = "GIT1passwordsnowflake"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
